services:
  - type: web
    name: score-analyzer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn flask_app:app --bind 0.0.0.0:$PORT --timeout 300 --keep-alive 30
    autoDeploy: true
